### ISSUE TITLE
Support netCDF4 in bald

### ISSUE THREAD

**Issue by lesserwhirls** [binary-array-ld/bald#64]
To reproduce:

run nc2rdf.py against a netCDF4 file. I triggered this using a GOES16 netCDF4 file from here:

http://thredds-test.unidata.ucar.edu/thredds/catalog/satellite/goes16/GOES16/CONUS/Channel01/catalog.html

error output:

~~~bash
python nc2rdf.py  ~/Downloads/GOES16_CONUS_20170810_020218_0.47_1km_33.3N_91.4W.nc4 --nc
Traceback (most recent call last):
  File "nc2rdf.py", line 41, in <module>
    nc2rdf(args.ncfile, args.format)
  File "nc2rdf.py", line 12, in nc2rdf
    root_container = bald.load_netcdf(ncfilename)
  File "/Users/sarms/miniconda3/envs/bald/lib/python3.6/site-packages/bald/__init__.py", line 539, in load_netcdf
    with load(afilepath) as fhandle:
  File "/Users/sarms/miniconda3/envs/bald/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/sarms/miniconda3/envs/bald/lib/python3.6/site-packages/bald/__init__.py", line 526, in load
    raise ValueError('filepath suffix not supported')
ValueError: filepath suffix not supported
~~~

**Comment by marqh** [comment]
this should be easy to fix, I'll get on this and update you
